// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: graph.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SnapshotWindow represents the time range for consistent snapshot reads.
// As queries traverse the graph, the window narrows to ensure consistency.
type SnapshotWindow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// min is the minimum store time we've committed to (state we've already used).
	Min uint64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	// max is the maximum store time we can use (replicated time ceiling).
	Max           uint64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotWindow) Reset() {
	*x = SnapshotWindow{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotWindow) ProtoMessage() {}

func (x *SnapshotWindow) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotWindow.ProtoReflect.Descriptor instead.
func (*SnapshotWindow) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotWindow) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SnapshotWindow) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// VisitedNode represents an (object_type, object_id, relation) triple that
// has already been visited in the current query traversal.
// Used for cycle detection across distributed nodes.
type VisitedNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object_type_id is the schema TypeID for the object type.
	ObjectTypeId uint32 `protobuf:"varint,1,opt,name=object_type_id,json=objectTypeId,proto3" json:"object_type_id,omitempty"`
	ObjectId     uint32 `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation_id is the schema RelationID for the relation.
	RelationId    uint32 `protobuf:"varint,3,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitedNode) Reset() {
	*x = VisitedNode{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitedNode) ProtoMessage() {}

func (x *VisitedNode) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitedNode.ProtoReflect.Descriptor instead.
func (*VisitedNode) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *VisitedNode) GetObjectTypeId() uint32 {
	if x != nil {
		return x.ObjectTypeId
	}
	return 0
}

func (x *VisitedNode) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *VisitedNode) GetRelationId() uint32 {
	if x != nil {
		return x.RelationId
	}
	return 0
}

// CheckRequest is the request to check if a subject has a relation on an object.
type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject_type_id is the schema TypeID for the subject type.
	SubjectTypeId uint32 `protobuf:"varint,1,opt,name=subject_type_id,json=subjectTypeId,proto3" json:"subject_type_id,omitempty"`
	SubjectId     uint32 `protobuf:"varint,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// object_type_id is the schema TypeID for the object type.
	ObjectTypeId uint32 `protobuf:"varint,3,opt,name=object_type_id,json=objectTypeId,proto3" json:"object_type_id,omitempty"`
	ObjectId     uint32 `protobuf:"varint,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation_id is the schema RelationID for the relation on object_type.
	RelationId uint32 `protobuf:"varint,5,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	// window constrains the snapshot for consistent reads across shards.
	Window *SnapshotWindow `protobuf:"bytes,6,opt,name=window,proto3" json:"window,omitempty"`
	// visited contains the nodes already visited in this query traversal.
	// Used for cycle detection across distributed nodes.
	Visited       []*VisitedNode `protobuf:"bytes,7,rep,name=visited,proto3" json:"visited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetSubjectTypeId() uint32 {
	if x != nil {
		return x.SubjectTypeId
	}
	return 0
}

func (x *CheckRequest) GetSubjectId() uint32 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *CheckRequest) GetObjectTypeId() uint32 {
	if x != nil {
		return x.ObjectTypeId
	}
	return 0
}

func (x *CheckRequest) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *CheckRequest) GetRelationId() uint32 {
	if x != nil {
		return x.RelationId
	}
	return 0
}

func (x *CheckRequest) GetWindow() *SnapshotWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *CheckRequest) GetVisited() []*VisitedNode {
	if x != nil {
		return x.Visited
	}
	return nil
}

// CheckResponse is the result of a relation check.
type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allowed is true if the subject has the relation on the object.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// window is the narrowed snapshot window after the check.
	// Subsequent queries should use this to maintain consistency.
	Window        *SnapshotWindow `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetWindow() *SnapshotWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

// RelationCheck represents a check against a single object type's relation.
// Used by CheckUnion to batch multiple checks with independent windows.
type RelationCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object_type_id is the schema TypeID for the object type.
	ObjectTypeId uint32 `protobuf:"varint,1,opt,name=object_type_id,json=objectTypeId,proto3" json:"object_type_id,omitempty"`
	// Serialized roaring bitmap of object IDs.
	ObjectIds []byte `protobuf:"bytes,2,opt,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	// relation_id is the schema RelationID for the relation on object_type.
	RelationId uint32 `protobuf:"varint,3,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	// Per-check window, narrowed based on reading this type's data.
	Window        *SnapshotWindow `protobuf:"bytes,4,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationCheck) Reset() {
	*x = RelationCheck{}
	mi := &file_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationCheck) ProtoMessage() {}

func (x *RelationCheck) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationCheck.ProtoReflect.Descriptor instead.
func (*RelationCheck) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{4}
}

func (x *RelationCheck) GetObjectTypeId() uint32 {
	if x != nil {
		return x.ObjectTypeId
	}
	return 0
}

func (x *RelationCheck) GetObjectIds() []byte {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *RelationCheck) GetRelationId() uint32 {
	if x != nil {
		return x.RelationId
	}
	return 0
}

func (x *RelationCheck) GetWindow() *SnapshotWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

// CheckUnionRequest checks if a subject has a relation on any of multiple objects.
// Each RelationCheck has its own snapshot window for independent narrowing.
type CheckUnionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject_type_id is the schema TypeID for the subject type.
	SubjectTypeId uint32 `protobuf:"varint,1,opt,name=subject_type_id,json=subjectTypeId,proto3" json:"subject_type_id,omitempty"`
	SubjectId     uint32 `protobuf:"varint,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// Checks to perform, each with its own object type, IDs, relation, and window.
	Checks []*RelationCheck `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	// visited contains the nodes already visited in this query traversal.
	Visited       []*VisitedNode `protobuf:"bytes,4,rep,name=visited,proto3" json:"visited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUnionRequest) Reset() {
	*x = CheckUnionRequest{}
	mi := &file_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUnionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUnionRequest) ProtoMessage() {}

func (x *CheckUnionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUnionRequest.ProtoReflect.Descriptor instead.
func (*CheckUnionRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUnionRequest) GetSubjectTypeId() uint32 {
	if x != nil {
		return x.SubjectTypeId
	}
	return 0
}

func (x *CheckUnionRequest) GetSubjectId() uint32 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *CheckUnionRequest) GetChecks() []*RelationCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *CheckUnionRequest) GetVisited() []*VisitedNode {
	if x != nil {
		return x.Visited
	}
	return nil
}

// DependentSet identifies objects that were relevant to a check result.
// Used for provenance tracking in snapshot window narrowing.
type DependentSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object_type_id is the schema TypeID for the object type.
	ObjectTypeId uint32 `protobuf:"varint,1,opt,name=object_type_id,json=objectTypeId,proto3" json:"object_type_id,omitempty"`
	// relation_id is the schema RelationID for the relation on object_type.
	RelationId uint32 `protobuf:"varint,2,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	// Serialized roaring bitmap of object IDs that were relevant.
	// If empty, means "all objects from the corresponding input check" (optimization).
	ObjectIds     []byte `protobuf:"bytes,3,opt,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependentSet) Reset() {
	*x = DependentSet{}
	mi := &file_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentSet) ProtoMessage() {}

func (x *DependentSet) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentSet.ProtoReflect.Descriptor instead.
func (*DependentSet) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{6}
}

func (x *DependentSet) GetObjectTypeId() uint32 {
	if x != nil {
		return x.ObjectTypeId
	}
	return 0
}

func (x *DependentSet) GetRelationId() uint32 {
	if x != nil {
		return x.RelationId
	}
	return 0
}

func (x *DependentSet) GetObjectIds() []byte {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

// CheckUnionResponse is the result of a union check.
type CheckUnionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allowed is true if the subject has the relation on ANY of the objects.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// window is the narrowed snapshot window after the check.
	// If found: window from the successful check.
	// If not found: tightest window across all checks.
	Window *SnapshotWindow `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	// dependent_sets identifies which object sets were relevant to the decision.
	// For found: single set with the matching object ID.
	// For not found: sets referencing all input checks (object_ids empty = all from input).
	DependentSets []*DependentSet `protobuf:"bytes,3,rep,name=dependent_sets,json=dependentSets,proto3" json:"dependent_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUnionResponse) Reset() {
	*x = CheckUnionResponse{}
	mi := &file_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUnionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUnionResponse) ProtoMessage() {}

func (x *CheckUnionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUnionResponse.ProtoReflect.Descriptor instead.
func (*CheckUnionResponse) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{7}
}

func (x *CheckUnionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckUnionResponse) GetWindow() *SnapshotWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *CheckUnionResponse) GetDependentSets() []*DependentSet {
	if x != nil {
		return x.DependentSets
	}
	return nil
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\ffalcon.graph\"4\n" +
	"\x0eSnapshotWindow\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x04R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x04R\x03max\"q\n" +
	"\vVisitedNode\x12$\n" +
	"\x0eobject_type_id\x18\x01 \x01(\rR\fobjectTypeId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\rR\bobjectId\x12\x1f\n" +
	"\vrelation_id\x18\x03 \x01(\rR\n" +
	"relationId\"\xa4\x02\n" +
	"\fCheckRequest\x12&\n" +
	"\x0fsubject_type_id\x18\x01 \x01(\rR\rsubjectTypeId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\rR\tsubjectId\x12$\n" +
	"\x0eobject_type_id\x18\x03 \x01(\rR\fobjectTypeId\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\rR\bobjectId\x12\x1f\n" +
	"\vrelation_id\x18\x05 \x01(\rR\n" +
	"relationId\x124\n" +
	"\x06window\x18\x06 \x01(\v2\x1c.falcon.graph.SnapshotWindowR\x06window\x123\n" +
	"\avisited\x18\a \x03(\v2\x19.falcon.graph.VisitedNodeR\avisited\"_\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x124\n" +
	"\x06window\x18\x02 \x01(\v2\x1c.falcon.graph.SnapshotWindowR\x06window\"\xab\x01\n" +
	"\rRelationCheck\x12$\n" +
	"\x0eobject_type_id\x18\x01 \x01(\rR\fobjectTypeId\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x02 \x01(\fR\tobjectIds\x12\x1f\n" +
	"\vrelation_id\x18\x03 \x01(\rR\n" +
	"relationId\x124\n" +
	"\x06window\x18\x04 \x01(\v2\x1c.falcon.graph.SnapshotWindowR\x06window\"\xc4\x01\n" +
	"\x11CheckUnionRequest\x12&\n" +
	"\x0fsubject_type_id\x18\x01 \x01(\rR\rsubjectTypeId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\rR\tsubjectId\x123\n" +
	"\x06checks\x18\x03 \x03(\v2\x1b.falcon.graph.RelationCheckR\x06checks\x123\n" +
	"\avisited\x18\x04 \x03(\v2\x19.falcon.graph.VisitedNodeR\avisited\"t\n" +
	"\fDependentSet\x12$\n" +
	"\x0eobject_type_id\x18\x01 \x01(\rR\fobjectTypeId\x12\x1f\n" +
	"\vrelation_id\x18\x02 \x01(\rR\n" +
	"relationId\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x03 \x01(\fR\tobjectIds\"\xa7\x01\n" +
	"\x12CheckUnionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x124\n" +
	"\x06window\x18\x02 \x01(\v2\x1c.falcon.graph.SnapshotWindowR\x06window\x12A\n" +
	"\x0edependent_sets\x18\x03 \x03(\v2\x1a.falcon.graph.DependentSetR\rdependentSets2\xa1\x01\n" +
	"\fGraphService\x12@\n" +
	"\x05Check\x12\x1a.falcon.graph.CheckRequest\x1a\x1b.falcon.graph.CheckResponse\x12O\n" +
	"\n" +
	"CheckUnion\x12\x1f.falcon.graph.CheckUnionRequest\x1a .falcon.graph.CheckUnionResponseB5Z3github.com/alechenninger/falcon/graph/proto;graphpbb\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_graph_proto_goTypes = []any{
	(*SnapshotWindow)(nil),     // 0: falcon.graph.SnapshotWindow
	(*VisitedNode)(nil),        // 1: falcon.graph.VisitedNode
	(*CheckRequest)(nil),       // 2: falcon.graph.CheckRequest
	(*CheckResponse)(nil),      // 3: falcon.graph.CheckResponse
	(*RelationCheck)(nil),      // 4: falcon.graph.RelationCheck
	(*CheckUnionRequest)(nil),  // 5: falcon.graph.CheckUnionRequest
	(*DependentSet)(nil),       // 6: falcon.graph.DependentSet
	(*CheckUnionResponse)(nil), // 7: falcon.graph.CheckUnionResponse
}
var file_graph_proto_depIdxs = []int32{
	0,  // 0: falcon.graph.CheckRequest.window:type_name -> falcon.graph.SnapshotWindow
	1,  // 1: falcon.graph.CheckRequest.visited:type_name -> falcon.graph.VisitedNode
	0,  // 2: falcon.graph.CheckResponse.window:type_name -> falcon.graph.SnapshotWindow
	0,  // 3: falcon.graph.RelationCheck.window:type_name -> falcon.graph.SnapshotWindow
	4,  // 4: falcon.graph.CheckUnionRequest.checks:type_name -> falcon.graph.RelationCheck
	1,  // 5: falcon.graph.CheckUnionRequest.visited:type_name -> falcon.graph.VisitedNode
	0,  // 6: falcon.graph.CheckUnionResponse.window:type_name -> falcon.graph.SnapshotWindow
	6,  // 7: falcon.graph.CheckUnionResponse.dependent_sets:type_name -> falcon.graph.DependentSet
	2,  // 8: falcon.graph.GraphService.Check:input_type -> falcon.graph.CheckRequest
	5,  // 9: falcon.graph.GraphService.CheckUnion:input_type -> falcon.graph.CheckUnionRequest
	3,  // 10: falcon.graph.GraphService.Check:output_type -> falcon.graph.CheckResponse
	7,  // 11: falcon.graph.GraphService.CheckUnion:output_type -> falcon.graph.CheckUnionResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
