// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: graph.proto

package graphpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphService_Check_FullMethodName      = "/falcon.graph.GraphService/Check"
	GraphService_CheckUnion_FullMethodName = "/falcon.graph.GraphService/CheckUnion"
)

// GraphServiceClient is the client API for GraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GraphService provides cross-node graph query operations.
// These RPCs mirror the Graph interface methods for distributed execution.
type GraphServiceClient interface {
	// Check determines if a subject has a relation on an object within a snapshot window.
	// This is called when traversing arrows or userset subjects that point to objects
	// on different shards.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// CheckUnion checks if a subject has a relation on any of the given objects.
	// This is used for scatter-gather: the caller groups objects by destination node,
	// then calls this RPC once per node with all relevant objects.
	// Returns true if the subject has the relation on ANY of the objects (short-circuits).
	// Each RelationCheck has its own snapshot window for independent narrowing.
	CheckUnion(ctx context.Context, in *CheckUnionRequest, opts ...grpc.CallOption) (*CheckUnionResponse, error)
}

type graphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphServiceClient(cc grpc.ClientConnInterface) GraphServiceClient {
	return &graphServiceClient{cc}
}

func (c *graphServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, GraphService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) CheckUnion(ctx context.Context, in *CheckUnionRequest, opts ...grpc.CallOption) (*CheckUnionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUnionResponse)
	err := c.cc.Invoke(ctx, GraphService_CheckUnion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphServiceServer is the server API for GraphService service.
// All implementations must embed UnimplementedGraphServiceServer
// for forward compatibility.
//
// GraphService provides cross-node graph query operations.
// These RPCs mirror the Graph interface methods for distributed execution.
type GraphServiceServer interface {
	// Check determines if a subject has a relation on an object within a snapshot window.
	// This is called when traversing arrows or userset subjects that point to objects
	// on different shards.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// CheckUnion checks if a subject has a relation on any of the given objects.
	// This is used for scatter-gather: the caller groups objects by destination node,
	// then calls this RPC once per node with all relevant objects.
	// Returns true if the subject has the relation on ANY of the objects (short-circuits).
	// Each RelationCheck has its own snapshot window for independent narrowing.
	CheckUnion(context.Context, *CheckUnionRequest) (*CheckUnionResponse, error)
	mustEmbedUnimplementedGraphServiceServer()
}

// UnimplementedGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphServiceServer struct{}

func (UnimplementedGraphServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedGraphServiceServer) CheckUnion(context.Context, *CheckUnionRequest) (*CheckUnionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUnion not implemented")
}
func (UnimplementedGraphServiceServer) mustEmbedUnimplementedGraphServiceServer() {}
func (UnimplementedGraphServiceServer) testEmbeddedByValue()                      {}

// UnsafeGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphServiceServer will
// result in compilation errors.
type UnsafeGraphServiceServer interface {
	mustEmbedUnimplementedGraphServiceServer()
}

func RegisterGraphServiceServer(s grpc.ServiceRegistrar, srv GraphServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphService_ServiceDesc, srv)
}

func _GraphService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_CheckUnion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUnionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).CheckUnion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_CheckUnion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).CheckUnion(ctx, req.(*CheckUnionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphService_ServiceDesc is the grpc.ServiceDesc for GraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "falcon.graph.GraphService",
	HandlerType: (*GraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _GraphService_Check_Handler,
		},
		{
			MethodName: "CheckUnion",
			Handler:    _GraphService_CheckUnion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graph.proto",
}
