// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: graph.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SnapshotWindow represents the time range for consistent snapshot reads.
// As queries traverse the graph, the window narrows to ensure consistency.
type SnapshotWindow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// min is the minimum store time we've committed to (state we've already used).
	Min uint64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	// max is the maximum store time we can use (replicated time ceiling).
	Max           uint64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotWindow) Reset() {
	*x = SnapshotWindow{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotWindow) ProtoMessage() {}

func (x *SnapshotWindow) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotWindow.ProtoReflect.Descriptor instead.
func (*SnapshotWindow) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotWindow) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SnapshotWindow) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// VisitedNode represents an (object_type, object_id, relation) triple that
// has already been visited in the current query traversal.
// Used for cycle detection across distributed nodes.
type VisitedNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      uint32                 `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitedNode) Reset() {
	*x = VisitedNode{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitedNode) ProtoMessage() {}

func (x *VisitedNode) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitedNode.ProtoReflect.Descriptor instead.
func (*VisitedNode) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *VisitedNode) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *VisitedNode) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *VisitedNode) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

// CheckRelationRequest is the request to check if a subject has a relation on an object.
type CheckRelationRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SubjectType string                 `protobuf:"bytes,1,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId   uint32                 `protobuf:"varint,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	ObjectType  string                 `protobuf:"bytes,3,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId    uint32                 `protobuf:"varint,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation    string                 `protobuf:"bytes,5,opt,name=relation,proto3" json:"relation,omitempty"`
	// window constrains the snapshot for consistent reads across shards.
	Window *SnapshotWindow `protobuf:"bytes,6,opt,name=window,proto3" json:"window,omitempty"`
	// visited contains the nodes already visited in this query traversal.
	// Used for cycle detection across distributed nodes.
	Visited       []*VisitedNode `protobuf:"bytes,7,rep,name=visited,proto3" json:"visited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRelationRequest) Reset() {
	*x = CheckRelationRequest{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRelationRequest) ProtoMessage() {}

func (x *CheckRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRelationRequest.ProtoReflect.Descriptor instead.
func (*CheckRelationRequest) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRelationRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *CheckRelationRequest) GetSubjectId() uint32 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *CheckRelationRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *CheckRelationRequest) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *CheckRelationRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRelationRequest) GetWindow() *SnapshotWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *CheckRelationRequest) GetVisited() []*VisitedNode {
	if x != nil {
		return x.Visited
	}
	return nil
}

// CheckRelationResponse is the result of a relation check.
type CheckRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allowed is true if the subject has the relation on the object.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// window is the narrowed snapshot window after the check.
	// Subsequent queries should use this to maintain consistency.
	Window        *SnapshotWindow `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRelationResponse) Reset() {
	*x = CheckRelationResponse{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRelationResponse) ProtoMessage() {}

func (x *CheckRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRelationResponse.ProtoReflect.Descriptor instead.
func (*CheckRelationResponse) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *CheckRelationResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckRelationResponse) GetWindow() *SnapshotWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\ffalcon.graph\"4\n" +
	"\x0eSnapshotWindow\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x04R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x04R\x03max\"g\n" +
	"\vVisitedNode\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\rR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\"\x9d\x02\n" +
	"\x14CheckRelationRequest\x12!\n" +
	"\fsubject_type\x18\x01 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\rR\tsubjectId\x12\x1f\n" +
	"\vobject_type\x18\x03 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\rR\bobjectId\x12\x1a\n" +
	"\brelation\x18\x05 \x01(\tR\brelation\x124\n" +
	"\x06window\x18\x06 \x01(\v2\x1c.falcon.graph.SnapshotWindowR\x06window\x123\n" +
	"\avisited\x18\a \x03(\v2\x19.falcon.graph.VisitedNodeR\avisited\"g\n" +
	"\x15CheckRelationResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x124\n" +
	"\x06window\x18\x02 \x01(\v2\x1c.falcon.graph.SnapshotWindowR\x06window2h\n" +
	"\fGraphService\x12X\n" +
	"\rCheckRelation\x12\".falcon.graph.CheckRelationRequest\x1a#.falcon.graph.CheckRelationResponseB5Z3github.com/alechenninger/falcon/graph/proto;graphpbb\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_graph_proto_goTypes = []any{
	(*SnapshotWindow)(nil),        // 0: falcon.graph.SnapshotWindow
	(*VisitedNode)(nil),           // 1: falcon.graph.VisitedNode
	(*CheckRelationRequest)(nil),  // 2: falcon.graph.CheckRelationRequest
	(*CheckRelationResponse)(nil), // 3: falcon.graph.CheckRelationResponse
}
var file_graph_proto_depIdxs = []int32{
	0, // 0: falcon.graph.CheckRelationRequest.window:type_name -> falcon.graph.SnapshotWindow
	1, // 1: falcon.graph.CheckRelationRequest.visited:type_name -> falcon.graph.VisitedNode
	0, // 2: falcon.graph.CheckRelationResponse.window:type_name -> falcon.graph.SnapshotWindow
	2, // 3: falcon.graph.GraphService.CheckRelation:input_type -> falcon.graph.CheckRelationRequest
	3, // 4: falcon.graph.GraphService.CheckRelation:output_type -> falcon.graph.CheckRelationResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
